## recover  

#### recover function  
```go
func t1() {
    defer fmt.Println("defer t1")
    fmt.Println("start t1")
    t2()
    fmt.Println("end t1")
}

func t2() {
    defer fmt.Println("defer t2")
    fmt.Println("start t2")
    t3()
    fmt.Println("end t2")
}

func t3() {
    defer fmt.Println("defer t3")
    defer executeRecover()
    fmt.Println("start t3")
    panic("프로그램 패닉 발생")
    fmt.Println("end t3")
}

func executeRecover() {
    recoverReturnValue := recover()
    if recoverReturnValue != nil {
        fmt.Println("recover return value:", recoverReturnValue)
    }
}

func main() {
    t1()
}

// start t1
// start t2
// start t3
// recover return value: 프로그램 패닉 발생
// defer t3
// end t2
// defer t2
// end t1
// defer t1
```
`recover()` 함수는 `panic()` 함수로 인해 프로그램이 종료되는 시점을 완화시키는 함수입니다.  
`panic()` 함수가 실행된 함수가 리턴되기 전에 `recover()` 함수를 호출하면 패닉 상태가 완화됩니다.  
반드시 패닉 상태가 활성화된 함수에서 `recover()` 함수를 호출해야만 효력이 있습니다.  
따라서 `t2()` 함수에서 `recover()` 함수를 호출하여도 아무런 효과를 기대할 수 없습니다.  
